// <auto-generated />
using System;
using MaiDan.Ordering.Dal;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using Microsoft.EntityFrameworkCore.Migrations;

namespace MaiDan.Ordering.Dal.Migrations
{
    [DbContext(typeof(OrderingContext))]
    [Migration("20180502215038_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.0-preview2-30571");

            modelBuilder.Entity("MaiDan.Ordering.Dal.Entities.Dish", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("OrderDish");
                });

            modelBuilder.Entity("MaiDan.Ordering.Dal.Entities.Line", b =>
                {
                    b.Property<int>("OrderId");

                    b.Property<int>("Index");

                    b.Property<string>("DishId")
                        .IsRequired();

                    b.Property<int>("Quantity");

                    b.HasKey("OrderId", "Index");

                    b.HasIndex("DishId");

                    b.ToTable("OrderLine");
                });

            modelBuilder.Entity("MaiDan.Ordering.Dal.Entities.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("Closed");

                    b.Property<int>("NumberOfGuests");

                    b.Property<string>("TableId");

                    b.Property<bool>("TakeAway");

                    b.HasKey("Id");

                    b.HasIndex("TableId");

                    b.ToTable("Order");
                });

            modelBuilder.Entity("MaiDan.Ordering.Dal.Entities.Table", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.HasKey("Id");

                    b.ToTable("Table");
                });

            modelBuilder.Entity("MaiDan.Ordering.Dal.Entities.Line", b =>
                {
                    b.HasOne("MaiDan.Ordering.Dal.Entities.Dish", "Dish")
                        .WithMany()
                        .HasForeignKey("DishId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("MaiDan.Ordering.Dal.Entities.Order")
                        .WithMany("Lines")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("MaiDan.Ordering.Dal.Entities.Order", b =>
                {
                    b.HasOne("MaiDan.Ordering.Dal.Entities.Table", "Table")
                        .WithMany()
                        .HasForeignKey("TableId");
                });
#pragma warning restore 612, 618
        }
    }
}
