// <auto-generated />
using System;
using MaiDan.Accounting.Dal;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace MaiDan.Accounting.Dal.Migrations
{
    [DbContext(typeof(AccountingContext))]
    partial class AccountingContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.0-rc1-32029");

            modelBuilder.Entity("MaiDan.Accounting.Dal.Entities.Payment", b =>
                {
                    b.Property<int>("SlipId");

                    b.Property<int>("Index");

                    b.Property<decimal>("Amount");

                    b.Property<string>("PaymentMethodId")
                        .IsRequired();

                    b.HasKey("SlipId", "Index");

                    b.HasIndex("PaymentMethodId");

                    b.ToTable("SlipPayment");
                });

            modelBuilder.Entity("MaiDan.Accounting.Dal.Entities.PaymentMethod", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("PaymentMethod");
                });

            modelBuilder.Entity("MaiDan.Accounting.Dal.Entities.Slip", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("PaymentDate");

                    b.HasKey("Id");

                    b.ToTable("Slip");
                });

            modelBuilder.Entity("MaiDan.Accounting.Dal.Entities.Payment", b =>
                {
                    b.HasOne("MaiDan.Accounting.Dal.Entities.PaymentMethod", "PaymentMethod")
                        .WithMany()
                        .HasForeignKey("PaymentMethodId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("MaiDan.Accounting.Dal.Entities.Slip")
                        .WithMany("Payments")
                        .HasForeignKey("SlipId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
