DROP TABLE IF EXISTS "Dish";
CREATE TABLE "Dish" 
	("Id" VARCHAR PRIMARY KEY  NOT NULL  UNIQUE ,
 	 "Name" VARCHAR);

DROP TABLE IF EXISTS "Table";
CREATE TABLE "Table" 
	("Id" VARCHAR PRIMARY KEY  NOT NULL  UNIQUE);
	
DROP TABLE IF EXISTS "Order";
CREATE TABLE "Order" 
	("Id" INTEGER PRIMARY KEY NOT NULL UNIQUE,
	 "TakeAway" INTEGER,
	 "TableId" VARCHAR,
	 "NumberOfGuests" INTEGER,
	FOREIGN KEY ("TableId") REFERENCES "Table"("Id"));

DROP TABLE IF EXISTS "OrderLine";
CREATE TABLE "OrderLine" 
	("OrderId" INTEGER NOT NULL, 
	 "DishId" VARCHAR NOT NULL, 
	 "Quantity" INTEGER NOT NULL,
	FOREIGN KEY("OrderId") REFERENCES "Order"("Id"),
	FOREIGN KEY("DishId") REFERENCES "Dish"("Id"));
