CREATE TABLE "Dish" ("Id" VARCHAR PRIMARY KEY  NOT NULL  UNIQUE , "Name" VARCHAR)

CREATE TABLE "Order" ("Id" TIMESTAMP PRIMARY KEY NOT NULL)

CREATE TABLE "Line" ("Id" INTEGER PRIMARY KEY NOT NULL, "OrderId" TIMESTAMP NOT NULL, FOREIGN KEY("OrderId") REFERENCES "Order"("Id"))