
DROP TABLE IF EXISTS "DishPrice";
DROP TABLE IF EXISTS "OrderLine";
DROP TABLE IF EXISTS "Dish";
DROP TABLE IF EXISTS "Order";
DROP TABLE IF EXISTS "Table";

CREATE TABLE "Dish" 
	("Id" VARCHAR PRIMARY KEY  NOT NULL  UNIQUE ,
 	 "Name" VARCHAR);

CREATE TABLE "DishPrice"
	("DishId" VARCHAR,
	 "ValidityStartDate" DATETIME,
	 "ValidityEndDate" DATETIME,
	 "Amount" REAL,
	FOREIGN KEY ("DishId") REFERENCES "Dish"("Id"));


CREATE TABLE "Table" 
	("Id" VARCHAR PRIMARY KEY  NOT NULL  UNIQUE);
	
CREATE TABLE "Order" 
	("Id" INTEGER PRIMARY KEY NOT NULL UNIQUE,
	 "TakeAway" INTEGER,
	 "TableId" VARCHAR,
	 "NumberOfGuests" INTEGER,
	FOREIGN KEY ("TableId") REFERENCES "Table"("Id"));

CREATE TABLE "OrderLine" 
	("Id" VARCHAR NOT NULL,
	 "OrderId" INTEGER NOT NULL, 
	 "Index" INTEGER NOT NULL,
	 "DishId" VARCHAR NOT NULL, 
	 "Quantity" INTEGER NOT NULL,
	FOREIGN KEY("OrderId") REFERENCES "Order"("Id"),
	FOREIGN KEY("DishId") REFERENCES "Dish"("Id"));
	
CREATE TABLE "Bill" 
	("Id" INTEGER PRIMARY KEY NOT NULL UNIQUE,
	 "Total" REAL NOT NULL,
	FOREIGN KEY ("Id") REFERENCES "Order"("Id"));

CREATE TABLE "BillLine" 
	("Id" VARCHAR NOT NULL,
	 "BillId" INTEGER NOT NULL, 
	 "Index" INTEGER NOT NULL,
	 "Amount" REAL NOT NULL, 
	FOREIGN KEY("BillId") REFERENCES "Bill"("Id"));

